QuickJSPP: qjs::Context Class Reference
qjs::Context Class Reference
Wrapper over JSContext * ctx Calls JS_SetContextOpaque(ctx, this); on construction and JS_FreeContext on destruction.
#include "quickjspp.hpp"
Classes
class Module
Module wrapper Workaround for lack of opaque pointer for module load function by keeping a list of modules in qjs::Context.
Public Member Functions
Context (Runtime &rt)
Context (JSRuntime *rt)
Context (JSContext *ctx)
Context (const Context &)=delete
~Context ()
Module & addModule (const char *name)
Create module and return a reference to it.
Value global ()
returns globalThis
Value newObject ()
returns new Object()
template<typename T >
Value newValue (T &&val)
returns JS value converted from c++ object val
Value getException ()
returns current exception associated with context, and resets it.
template<class T >
void registerClass (const char *name, JSValue proto=JS_NULL)
Register class T for conversions to/from std::shared_ptr<T> to work.
Value eval (std::string_view buffer, const char *filename="<eval>", unsigned eval_flags=0)
Value evalFile (const char *filename, unsigned eval_flags=0)
Value fromJSON (std::string_view buffer, const char *filename="<fromJSON>")
Static Public Member Functions
static Context & get (JSContext *ctx)
Get qjs::Context from JSContext opaque pointer.
Public Attributes
JSContext * ctx
std::vector< Module, allocator< Module > > modules
Private Member Functions
void init ()
Detailed Description
Wrapper over JSContext * ctx Calls JS_SetContextOpaque(ctx, this); on construction and JS_FreeContext on destruction.
Definition at line 969 of file quickjspp.hpp.
Constructor & Destructor Documentation
Context() [1/4]
qjs::Context::Context (Runtime & rt) inline
Definition at line 1158 of file quickjspp.hpp.
References Context(), and qjs::Runtime::rt.
Referenced by main().
                          : Context(rt.rt)
     {}
Context() [2/4]
qjs::Context::Context (JSRuntime * rt) inline
Definition at line 1161 of file quickjspp.hpp.
References modules.
Referenced by Context().
                             : modules{rt}
     {
         ctx = JS_NewContext(rt);
         if(!ctx)
             throw std::runtime_error{"qjs: Cannot create context"};
         init();
     }
Context() [3/4]
qjs::Context::Context (JSContext * ctx) inline
Definition at line 1169 of file quickjspp.hpp.
References ctx.
                              : ctx{ctx}, modules{ctx}
     {
         init();
     }
Context() [4/4]
qjs::Context::Context (const Context &) delete
~Context()
qjs::Context::~Context () inline
Definition at line 1177 of file quickjspp.hpp.
References ctx, JS_FreeContext(), and modules.
     {
         modules.clear();
         JS_FreeContext(ctx);
     }
Member Function Documentation
init()
void qjs::Context::init () inline private
Definition at line 1151 of file quickjspp.hpp.
References ctx, JS_SetContextOpaque(), and qjs::js_traits< detail::function >::register_class().
     {
         JS_SetContextOpaque(ctx, this);
         js_traits<detail::function>::register_class(ctx, "C++ function");
     }
addModule()
Module& qjs::Context::addModule (const char * name) inline
Create module and return a reference to it.
Definition at line 1184 of file quickjspp.hpp.
References ctx, and modules.
     {
         modules.emplace_back(ctx, name);
         return modules.back();
     }
global()
Value qjs::Context::global () inline
returns globalThis
Definition at line 1191 of file quickjspp.hpp.
References ctx, JS_GetGlobalObject(), and qjs::Value::Value().
 { return Value{ctx, JS_GetGlobalObject(ctx)}; }
newObject()
Value qjs::Context::newObject () inline
returns new Object()
Definition at line 1194 of file quickjspp.hpp.
References ctx, JS_NewObject(), and qjs::Value::Value().
Referenced by qjs::Context::Module::class_registrar< T >::class_registrar().
 { return Value{ctx, JS_NewObject(ctx)}; }
newValue()
template<typename T > Value qjs::Context::newValue (T && val) inline
returns JS value converted from c++ object val
Definition at line 1198 of file quickjspp.hpp.
References ctx.
 { return Value{ctx, std::forward<T>(val)}; }
getException()
Value qjs::Context::getException () inline
returns current exception associated with context, and resets it.
Should be called when qjs::exception is caught
Definition at line 1201 of file quickjspp.hpp.
References ctx, JS_GetException(), and qjs::Value::Value().
Referenced by main().
 { return Value{ctx, JS_GetException(ctx)}; }
registerClass()
template<class T > void qjs::Context::registerClass (const char * name, JSValue proto = JS_NULL) inline
Register class T for conversions to/from std::shared_ptr<T> to work.
Wherever possible module.class_<T>("T")... should be used instead.
Template Parameters
T class type
Parameters
name class name in JS engine
proto JS class prototype or JS_UNDEFINED
Definition at line 1210 of file quickjspp.hpp.
References ctx.
     {
         js_traits<std::shared_ptr<T>>::register_class(ctx, name, proto);
     }
eval()
Value qjs::Context::eval (std::string_view buffer, const char * filename = "<eval>", unsigned eval_flags = 0) inline
Definition at line 1215 of file quickjspp.hpp.
References ctx, JS_Eval(), and qjs::Value::Value().
Referenced by evalFile(), and main().
     {
         assert(buffer.data()[buffer.size()] == '\0' && "eval buffer is not null-terminated"); // JS_Eval requirement
         JSValue v = JS_Eval(ctx, buffer.data(), buffer.size(), filename, eval_flags);
         return Value{ctx, v};
     }
evalFile()
Value qjs::Context::evalFile (const char * filename, unsigned eval_flags = 0) inline
Definition at line 1222 of file quickjspp.hpp.
References ctx, eval(), js_free(), and js_load_file().
Referenced by main().
     {
         size_t buf_len;
         auto deleter = [this](void * p) { js_free(ctx, p); };
         auto buf = std::unique_ptr<uint8_t, decltype(deleter)>{js_load_file(ctx, &buf_len, filename), deleter};
         if(!buf)
             throw std::runtime_error{std::string{"evalFile: can't read file: "} + filename};
         return eval({reinterpret_cast<char *>(buf.get()), buf_len}, filename, eval_flags);
     }
fromJSON()
Value qjs::Context::fromJSON (std::string_view buffer, const char * filename = "<fromJSON>") inline
Definition at line 1232 of file quickjspp.hpp.
References ctx, JS_ParseJSON(), and qjs::Value::Value().
     {
         assert(buffer.data()[buffer.size()] == '\0' && "fromJSON buffer is not null-terminated"); // JS_ParseJSON requirement
         JSValue v = JS_ParseJSON(ctx, buffer.data(), buffer.size(), filename);
         return Value{ctx, v};
     }
get()
static Context& qjs::Context::get (JSContext * ctx) inline static
Get qjs::Context from JSContext opaque pointer.
Definition at line 1240 of file quickjspp.hpp.
References JS_GetContextOpaque().
Referenced by qjs::Context::Module::class_(), and qjs::Context::Module::Module().
     {
         void * ptr = JS_GetContextOpaque(ctx);
         assert(ptr);
         return *reinterpret_cast<Context *>(ptr);
     }
Member Data Documentation
ctx
JSContext* qjs::Context::ctx
Definition at line 972 of file quickjspp.hpp.
Referenced by addModule(), qjs::Context::Module::class_registrar< T >::constructor(), Context(), eval(), evalFile(), fromJSON(), getException(), global(), init(), main(), newObject(), newValue(), registerClass(), and ~Context().
modules
std::vector<Module, allocator<Module> > qjs::Context::modules
Definition at line 1149 of file quickjspp.hpp.
Referenced by addModule(), Context(), qjs::Context::Module::Module(), and ~Context().
The documentation for this class was generated from the following file:
quickjspp.hpp