QuickJSPP: qjs::Context::Module Class Reference
qjs::Context::Module Class Reference
Module wrapper Workaround for lack of opaque pointer for module load function by keeping a list of modules in qjs::Context.
#include "quickjspp.hpp"
Classes
class class_registrar
Helper class to register class members and constructors.
Public Member Functions
Module (JSContext *ctx, const char *name)
Module & add (const char *name, JSValue value)
Module & add (const char *name, Value value)
template<typename T >
Module & add (const char *name, T value)
Module (const Module &)=delete
Module (Module &&)=default
template<auto F>
Module & function (const char *name)
Add free function F.
template<typename F >
Module & function (const char *name, F &&f)
Add function object f.
template<class T >
class_registrar< T > class_ (const char *name)
Add class to module.
Private Types
using nvp = std::pair< const char *, Value >
Private Attributes
JSModuleDef * m
JSContext * ctx
const char * name
std::vector< nvp, allocator< nvp > > exports
Friends
class Context
Detailed Description
Module wrapper Workaround for lack of opaque pointer for module load function by keeping a list of modules in qjs::Context.
Definition at line 977 of file quickjspp.hpp.
Member Typedef Documentation
nvp
using qjs::Context::Module::nvp = std::pair<const char *, Value> private
Definition at line 985 of file quickjspp.hpp.
Constructor & Destructor Documentation
Module() [1/3]
qjs::Context::Module::Module (JSContext * ctx, const char * name) inline
Definition at line 988 of file quickjspp.hpp.
References ctx, exports, qjs::Context::get(), JS_DupValue(), JS_GetRuntime(), JS_NewCModule(), JS_SetModuleExport(), m, qjs::Context::modules, name, and qjs::Value::v.
                                                    : ctx(ctx), name(name), exports(JS_GetRuntime(ctx))
         {
             m = JS_NewCModule(ctx, name, [](JSContext * ctx, JSModuleDef * m) noexcept {
                 auto& context = Context::get(ctx);
                 auto it = std::find_if(context.modules.begin(), context.modules.end(),
                                        [m](const Module& module) { return module.m == m; });
                 if(it == context.modules.end())
                     return -1;
                 for(const auto& e : it->exports)
                 {
                     if(JS_SetModuleExport(ctx, m, e.first, JS_DupValue(ctx, e.second.v)) != 0)
                         return -1;
                 }
                 return 0;
             });
             if(!m)
                 throw exception{};
         }
Module() [2/3]
qjs::Context::Module::Module (const Module &) delete
Module() [3/3]
qjs::Context::Module::Module (Module &&) default
Member Function Documentation
add() [1/3]
Module& qjs::Context::Module::add (const char * name, JSValue value) inline
Definition at line 1007 of file quickjspp.hpp.
References ctx, exports, JS_AddModuleExport(), m, and qjs::Value::Value().
         {
             exports.push_back({name, {ctx, value}});
             JS_AddModuleExport(ctx, m, name);
             return *this;
         }
add() [2/3]
Module& qjs::Context::Module::add (const char * name, Value value) inline
Definition at line 1014 of file quickjspp.hpp.
References qjs::Value::ctx, ctx, exports, JS_AddModuleExport(), and m.
         {
             assert(value.ctx == ctx);
             exports.push_back({name, std::move(value)});
             JS_AddModuleExport(ctx, m, name);
             return *this;
         }
add() [3/3]
template<typename T > Module& qjs::Context::Module::add (const char * name, T value) inline
Definition at line 1023 of file quickjspp.hpp.
References ctx.
         {
             return add(name, js_traits<T>::wrap(ctx, std::move(value)));
         }
function() [1/2]
template<auto F> Module& qjs::Context::Module::function (const char * name) inline
Add free function F.
Example: module.function<static_cast<double (*)(double)>(&::sin)>("sin");
Definition at line 1041 of file quickjspp.hpp.
         {
             return add(name, qjs::fwrapper<F>{name});
         }
function() [2/2]
template<typename F > Module& qjs::Context::Module::function (const char * name, F && f) inline
Add function object f.
Slower than template version. Example: module.function("sin", [](double x) { return ::sin(x); });
Definition at line 1051 of file quickjspp.hpp.
         {
             return add(name, js_traits<decltype(std::function{std::forward<F>(f)})>::wrap(std::forward<F>(f)));
         }
class_()
template<class T > class_registrar<T> qjs::Context::Module::class_ (const char * name) inline
Add class to module.
See class_registrar.
Definition at line 1142 of file quickjspp.hpp.
References ctx, and qjs::Context::get().
         {
             return class_registrar<T>{name, *this, qjs::Context::get(ctx)};
         }
Friends And Related Function Documentation
Context
friend class Context friend
Definition at line 979 of file quickjspp.hpp.
Member Data Documentation
m
JSModuleDef* qjs::Context::Module::m private
Definition at line 981 of file quickjspp.hpp.
Referenced by add(), and Module().
ctx
JSContext* qjs::Context::Module::ctx private
Definition at line 982 of file quickjspp.hpp.
Referenced by add(), class_(), and Module().
name
const char* qjs::Context::Module::name private
Definition at line 983 of file quickjspp.hpp.
Referenced by Module().
exports
std::vector<nvp, allocator<nvp> > qjs::Context::Module::exports private
Definition at line 986 of file quickjspp.hpp.
Referenced by add(), and Module().
The documentation for this class was generated from the following file:
quickjspp.hpp