QuickJSPP: qjs::js_traits< std::vector< T > > Struct Template Reference
qjs::js_traits< std::vector< T > > Struct Template Reference
Convert from std::vector<T> to Array and vice-versa.
#include "quickjspp.hpp"
Static Public Member Functions
static JSValue wrap (JSContext *ctx, const std::vector< T > &arr) noexcept
static std::vector< T > unwrap (JSContext *ctx, JSValueConst jsarr)
Detailed Description
template<class T>
struct qjs::js_traits< std::vector< T > >
Convert from std::vector<T> to Array and vice-versa.
If Array holds objects that are non-convertible to T throws qjs::exception
Definition at line 1308 of file quickjspp.hpp.
Member Function Documentation
wrap()
template<class T > static JSValue qjs::js_traits< std::vector< T > >::wrap (JSContext * ctx, const std::vector< T > & arr) inline static noexcept
Definition at line 1310 of file quickjspp.hpp.
References JS_IsException(), JS_NewArray(), qjs::Value::operator[](), qjs::Value::v, and qjs::Value::Value().
     {
         auto jsarray = Value{ctx, JS_NewArray(ctx)};
         if(JS_IsException(jsarray.v))
             return jsarray.v;
         try
         {
             for(uint32_t i = 0; i < (uint32_t) arr.size(); i++)
                 jsarray[i] = arr[i];
         }
         catch(exception)
         {
             return JS_EXCEPTION;
         }
         return std::move(jsarray);
     }
unwrap()
template<class T > static std::vector<T> qjs::js_traits< std::vector< T > >::unwrap (JSContext * ctx, JSValueConst jsarr) inline static
Definition at line 1328 of file quickjspp.hpp.
References JS_DupValue(), JS_IsArray(), qjs::Value::operator[](), and qjs::Value::Value().
     {
         int e = JS_IsArray(ctx, jsarr);
         if(e == 0)
             JS_ThrowTypeError(ctx, "js_traits<std::vector<T>>::unwrap expects array");
         if(e <= 0)
             throw exception{};
         Value jsarray{ctx, JS_DupValue(ctx, jsarr)};
         std::vector<T> arr;
         auto len = static_cast<int32_t>(jsarray["length"]);
         arr.reserve((uint32_t) len);
         for(uint32_t i = 0; i < (uint32_t) len; i++)
             arr.push_back(static_cast<T>(jsarray[i]));
         return arr;
     }
The documentation for this struct was generated from the following file:
quickjspp.hpp