QuickJSPP: qjs::js_traits< std::shared_ptr< T > > Struct Template Reference
qjs::js_traits< std::shared_ptr< T > > Struct Template Reference
Conversions for std::shared_ptr<T>.
#include "quickjspp.hpp"
Static Public Member Functions
static void register_class (JSContext *ctx, const char *name, JSValue proto=JS_NULL)
Register class in QuickJS context.
static JSValue wrap (JSContext *ctx, std::shared_ptr< T > ptr)
Create a JSValue from std::shared_ptr<T>.
static const std::shared_ptr< T > & unwrap (JSContext *ctx, JSValueConst v)
Static Public Attributes
static JSClassID QJSClassId = 0
Registered class id in QuickJS.
Detailed Description
template<class T>
struct qjs::js_traits< std::shared_ptr< T > >
Conversions for std::shared_ptr<T>.
T should be registered to a context before conversions.
Template Parameters
T class type
Definition at line 495 of file quickjspp.hpp.
Member Function Documentation
register_class()
template<class T > static void qjs::js_traits< std::shared_ptr< T > >::register_class (JSContext * ctx, const char * name, JSValue proto = JS_NULL) inline static
Register class in QuickJS context.
Parameters
ctx context
name class name
proto class prototype or JS_NULL
Exceptions
exception
Definition at line 507 of file quickjspp.hpp.
References __attribute__(), JS_GetOpaque(), JS_GetRuntime(), JS_IsRegisteredClass(), JS_NewClass(), JS_NewClassID(), JS_SetClassProto(), and QJSClassId.
Referenced by wrap().
     {
         if(QJSClassId == 0)
         {
             JS_NewClassID(&QJSClassId);
         }
         auto rt = JS_GetRuntime(ctx);
         if(!JS_IsRegisteredClass(rt, QJSClassId))
         {
             JSClassDef def{
                     name,
                     // destructor
                     [](JSRuntime * rt, JSValue obj) noexcept {
                         auto pptr = reinterpret_cast<std::shared_ptr<T> *>(JS_GetOpaque(obj, QJSClassId));
                         assert(pptr);
                         //delete pptr;
                         auto alloc = allocator<std::shared_ptr<T>>{rt};
                         using atraits = std::allocator_traits<decltype(alloc)>;
                         atraits::destroy(alloc, pptr);
                         atraits::deallocate(alloc, pptr, 1);
                     }
             };
             int e = JS_NewClass(rt, QJSClassId, &def);
             if(e < 0)
             {
                 JS_ThrowInternalError(ctx, "Cant register class %s", name);
                 throw exception{};
             }
         }
         JS_SetClassProto(ctx, QJSClassId, proto);
     }
wrap()
template<class T > static JSValue qjs::js_traits< std::shared_ptr< T > >::wrap (JSContext * ctx, std::shared_ptr< T > ptr) inline static
Create a JSValue from std::shared_ptr<T>.
Creates an object with class if QJSClassId and sets its opaque pointer to a new copy of #ptr.
Definition at line 542 of file quickjspp.hpp.
References JS_IsException(), JS_NewObjectClass(), QJSClassId, and register_class().
     {
         if(QJSClassId == 0) // not registered
         {
             register_class(ctx, typeid(T).name());
             //JS_ThrowTypeError(ctx, "quickjspp: Class %s is not registered", typeid(T).name());
             //return JS_EXCEPTION;
         }
         auto jsobj = JS_NewObjectClass(ctx, QJSClassId);
         if(JS_IsException(jsobj))
         {
             return jsobj;
         }
         //auto pptr = new std::shared_ptr<T>(std::move(ptr));
         auto alloc = allocator<std::shared_ptr<T>>{ctx};
         using atraits = std::allocator_traits<decltype(alloc)>;
         auto pptr = atraits::allocate(alloc, 1);
         atraits::construct(alloc, pptr, std::move(ptr));
         JS_SetOpaque(jsobj, pptr);
         return jsobj;
     }
unwrap()
template<class T > static const std::shared_ptr<T>& qjs::js_traits< std::shared_ptr< T > >::unwrap (JSContext * ctx, JSValueConst v) inline static
Exceptions
exception if #v doesn't have the correct class id
Definition at line 566 of file quickjspp.hpp.
References JS_GetOpaque2(), and QJSClassId.
     {
         auto ptr = reinterpret_cast<std::shared_ptr<T> *>(JS_GetOpaque2(ctx, v, QJSClassId));
         if(!ptr)
             throw exception{};
         return *ptr;
     }
Member Data Documentation
QJSClassId
template<class T > JSClassID qjs::js_traits< std::shared_ptr< T > >::QJSClassId = 0 inline static
Registered class id in QuickJS.
Definition at line 498 of file quickjspp.hpp.
Referenced by register_class(), unwrap(), and wrap().
The documentation for this struct was generated from the following file:
quickjspp.hpp