QuickJSPP: qjs::js_traits< ctor_wrapper< T, Args... > > Struct Template Reference
qjs::js_traits< ctor_wrapper< T, Args... > > Struct Template Reference
Conversion to JSValue for ctor_wrapper.
#include "quickjspp.hpp"
Static Public Member Functions
static JSValue wrap (JSContext *ctx, ctor_wrapper< T, Args... > cw) noexcept
Detailed Description
template<class T, typename... Args>
struct qjs::js_traits< ctor_wrapper< T, Args... > >
Conversion to JSValue for ctor_wrapper.
Definition at line 451 of file quickjspp.hpp.
Member Function Documentation
wrap()
template<class T , typename... Args> static JSValue qjs::js_traits< ctor_wrapper< T, Args... > >::wrap (JSContext * ctx, ctor_wrapper< T, Args... > cw) inline static noexcept
Definition at line 453 of file quickjspp.hpp.
References JS_CFUNC_constructor, JS_FreeValue(), JS_GetPropertyStr(), and JS_IsException().
     {
         return JS_NewCFunction2(ctx, [](JSContext * ctx, JSValueConst this_value, int argc,
                                         JSValueConst * argv) noexcept -> JSValue {
             std::shared_ptr<T> ptr =  std::apply(std::make_shared<T, Args...>, detail::unwrap_args<Args...>(ctx, argv));
             if(js_traits<std::shared_ptr<T>>::QJSClassId == 0) // not registered
             {
                 js_traits<std::shared_ptr<T>>::register_class(ctx, typeid(T).name());
                 //JS_ThrowTypeError(ctx, "quickjspp: Class %s is not registered", typeid(T).name());
                 //return JS_EXCEPTION;
             }
             auto proto = JS_GetPropertyStr(ctx, this_value, "prototype");
             if (JS_IsException(proto))
                 return proto;
             auto jsobj = JS_NewObjectProtoClass(ctx, proto, js_traits<std::shared_ptr<T>>::QJSClassId);
             JS_FreeValue(ctx, proto);
             if (JS_IsException(jsobj))
                 return jsobj;
             //auto pptr = new std::shared_ptr<T>(std::move(ptr));
             auto alloc = allocator<std::shared_ptr<T>>{ctx};
             using atraits = std::allocator_traits<decltype(alloc)>;
             auto pptr = atraits::allocate(alloc, 1);
             atraits::construct(alloc, pptr, std::move(ptr));
             JS_SetOpaque(jsobj, pptr);
             return jsobj;
             // return detail::wrap_call<std::shared_ptr<T>, Args...>(ctx, std::make_shared<T, Args...>, argv);
         }, cw.name, sizeof...(Args), JS_CFUNC_constructor, 0);
     }
The documentation for this struct was generated from the following file:
quickjspp.hpp